In [40]:
import pandas as pd
import seaborn as sns
import numpy as np
import math

#to apply normalization and standarization
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_selector as selector

from sklearn import linear_model

#encoding categorical variables 
from sklearn.preprocessing import OneHotEncoder

#to build and validate a KNN model
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
#from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [41]:
dfa = pd.read_csv('df_encoding3_1.csv')
dfa.head(2)

journey_year  journey_month  journey_day  weekday  dep_hour  dep_min  \
0          2019              3           24        6        22       20   
1          2019              1            5        5         5       50   

   Arrival_hour  Arrival_min  Arrived_next_day  duration_hours  ...  \
0             1           10                 1               2  ...   
1            13           15                 0               7  ...   

   departure_evening  departure_late night  departure_morning  \
0                  0                     0                  0   
1                  0                     0                  0   

   departure_night  arrival_After noon  arrival_early morning  \
0                1                   0                      0   
1                0                   1                      0   

   arrival_evening  arrival_late night  arrival_morning  arrival_night  
0                0                   1                0              0  
1                0                   0                0              0  

[2 rows x 52 columns]

Cross validation

In [49]:
P_features = pd.read_csv('P_features.csv')
P_target = pd.read_csv('P_target.csv')

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(P_features,P_target,test_size=0.3)

In [51]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/opt/conda/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.33354571519592224

In [52]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

/opt/conda/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.21280662631411276

In [53]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

/tmp/ipykernel_475/2692549809.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


0.3408728894552405

In [3]:
train, test = train_test_split(dfa, train_size=0.7, random_state=123)


In [4]:
X_train = train.drop("price", axis=1)
y_train = train[["price"]]

In [16]:
reg = linear_model.LinearRegression()


In [36]:
reg.fit(dfa[['journey_year','journey_month','journey_day','weekday','dep_hour','dep_min','Arrival_hour','Arrival_min','Arrived_next_day','duration_hours','duration_mins','Duration_in_mins','Air Asia','Air India','GoAir',	'IndiGo',	'Jet Airways',	'Jet Airways Business',	'Multiple carriers',	'Multiple carriers Premium economy',	'SpiceJet',	'Trujet',	'Vistara',	'Vistara Premium economy',	'destination_Banglore',	'destination_Cochin',	'destination_Delhi',	'destination_Hyderabad',	'destination_Kolkata',	'source_Banglore',	'source_Chennai',	'source_Delhi',	'source_Kolkata',	'source_Mumbai',	'1 stop',	'2 stops',	'3 stops',	'4 stops',	'non-stop',	'departure_After noon',	'departure_early morning','departure_evening','departure_late night','departure_morning','departure_night','arrival_After noon','arrival_early morning','arrival_evening','arrival_late night','arrival_morning','arrival_night'
]],dfa.price)

LinearRegression()

In [37]:
reg.coef_

array([-5.58177479e-11, -1.24421208e+02, -8.13323840e+01, -7.72984111e+01,
        3.24719394e+01,  3.93889657e+00, -1.62279735e+02,  3.78655131e+00,
       -1.60860124e+03,  4.34111831e-02, -1.56147517e+00,  1.04319571e+00,
       -5.27632227e+03, -3.59043725e+03, -5.56670517e+03, -4.98471834e+03,
       -1.11701125e+03,  4.29137253e+04, -1.94629310e+03, -8.45080182e+02,
       -5.39532925e+03, -9.22795214e+03, -3.15400037e+03, -1.80987594e+03,
       -1.21908303e+02, -1.76656041e+02,  4.39079487e+02, -5.08386258e+02,
        3.67871114e+02,  4.39079487e+02,  3.67871114e+02, -1.76656041e+02,
       -1.21908303e+02, -5.08386258e+02, -1.54308884e+03,  7.42536992e+02,
        2.02962367e+03,  4.72286923e+03, -5.95194105e+03,  3.20575931e+02,
       -5.06629063e+02,  6.90491868e+01, -4.18087651e+02, -1.00556044e+02,
        6.35647641e+02,  1.95581533e+02, -2.07663562e+02,  8.63474177e+02,
       -9.56206271e+02, -3.60840800e+02,  4.65654924e+02])

In [19]:
reg.intercept_

16885.35721537547

In [38]:
reg.predict([[2019,	3,	24,	6,	22,	20,	1,	10,	1,	2,	50,	170,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	1,	0,	0,	0,1,	0,	0,
]])

array([4293.3753164])

In [39]:
reg.predict([[2019,	3,	4,	0,	11,	40,	14,	30,	0,	2,	50,	170,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	1,	0,	1,	0,	0,	0,	0,	0,
]])

array([5513.69305862])